### ISSUE TITLE
nuc980的rtt系统emac驱动问题

### ISSUE THREAD

**Issue by tomyqg** [wosayttn/NUemWin#1]
大佬，你搞得nuc980的rtt的emac为啥开启pdma内存拷贝后，iperf测速很慢啊，关掉pdma内存拷贝后才可以

**Comment by wosayttn** [comment]
是的，實測確實如此; 但換個方式想，把 CPU resource 讓出來，不使用 memory-copy 讓應用享用多一點。
如果想讓數據快一些，可關閉 PDMA 的 Data-copying。
